### PR TITLE
Remove deprecated Python 3.3 test

### PR DESCRIPTION
**Pull request by szepeviktor**
See [Travis output](https://travis-ci.org/UpCloudLtd/upcloud-python-api/jobs/403491420)

### CODE REVIEW

**Comment by cancerballs** [comment]
Thank you!

**Comment by szepeviktor** [comment]
@cancerballs Closing was your intention?

**Comment by cancerballs** [comment]
This was an honest misclick. I meant to merge this into Master. This can't be reopened because the branch has been deleted. Can you create a new issue with the same patch and I'll merge it into Master.

**Comment by szepeviktor** [comment]
I've deleted the branch thinking you've merged it manually into master.

**Pull request closed without merging**
