### PR TITLE
Remove deprecated Python 3.3 test

### PR DESCRIPTION
**Pull request by szepeviktor**
Was #50 

@cancerballs You may fetch a PR by

```
git fetch origin pull/50/head:pull-50
git checkout pull-50
```

https://help.github.com/articles/checking-out-pull-requests-locally/

### CODE REVIEW

**Comment by cancerballs** [comment]
Thank you again and sorry for the confusion earlier.

**Comment by szepeviktor** [comment]
@cancerballs You're welcome.
Could you take care of the integration tests?
Maybe the secret environment variables have a problem.

**Comment by cancerballs** [comment]
Yeah I got it. The issue is the time out which I increased in a previous merge before this. I'll try to trigger the build to run again which should fix it.

**Comment by szepeviktor** [comment]
Seems to be all green.

**Pull request merged**
